[package]
name = "thu-polylux"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["duskmoon (Campbell He) <kp.campbell.he@duskmoon314.com>"]
license = "MIT"
description = "THU Polylux theme template"

[template]
path = "template"
entrypoint = "main.typ"
